module.exports = {

    ORGANIZATION_TYPE:{
        FINANCER: "FINANCER",
        BUYER: "BUYER",
        COUNTER: "COUNTER",
        SELLER: "SELLER",
        DISTRIBUTOR : "DISTRIBUTOR",
        ACCOUNTANT: "ACCOUNTANT",
        ORDER_MANAGER: "ORDER_MANAGER"
    },
    ROLE:{
        ACCOUNTANT: "ACCOUNTANT",
        ORDER_MANAGER: "ORDER_MANAGER"
    },
    INVOICE_TYPE:{
        PAYABLE_INVOICE: "PAYABLE_INVOICE",
        INVOICE_DISCOUNTING: "INVOICE_DISCOUNTING",
        DISTRIBUTOR_FINANCING: "DISTRIBUTOR_FINANCING"
    },
    STATUS:{
        REQUESTING: "REQUESTING",
        ACCEPTED: "ACCEPTED",
        REJECTED: "REJECTED",
        CLOSED: "CLOSED",
        ACTIVE: "ACTIVE",
        FINANCED: "FINANCED"
    },
    TOOL:{
        INVOICE: "INVOICE",
        PURCHASE_ORDER: "PURCHASE_ORDER"
    }
}